import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Harrison Couto</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body style={{ backgroundColor: '#121826' }} suppressHydrationWarning={true} className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
